---
- name: AWS CloudTrail
  hosts: all
  sources:
    - name: Connect to AWS CloudTrail
      ansible.eda.aws_cloudtrail:
        region: "{{ region }}"
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_key }}"

  rules:
    - name: Display payload
      condition: event.payload is defined
      action:
       debug:
         msg: ">>> Received event! {{ event.payload }}"

    - name: Remove instances with not approved images (Ubuntu)
      condition: event.CloudTrailEvent.requestParameters.instancesSet.items[0].imageId == "ami-09e647bf7a368e505"
      action:
        run_job_template:
          name: "[EDA] Cloudtrail"
          organization: Default
          job_args:
            extra_vars:
              remove: true
              type: ec2
              instance_name: "{{ event['CloudTrailEvent']['requestParameters']['tagSpecificationSet']['items'][0]['tags'][0]['value'] }}"
